#=========================================================================
# LVS using netgen
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

name: open-netgen-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_extracted.spice
  - design.lvs.v

outputs:
  - lvs_results.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands: 
  - v2lvs -i -lsp inputs/adk/stdcells.spi -s inputs/adk/stdcells.spi -lsp inputs/*.sp -s inputs/*.sp -v inputs/design.lvs.v -o design_lvs.spice
  #- cat inputs/adk/netgen-setup.tcl > netgen_blackbox_setup.tcl
  - cat inputs/adk/netgen-setup.tcl blackbox.tcl > netgen_blackbox_setup.tcl
  - sh run_lvs.sh

