#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Kartik Prabhu
# Date   : February 15, 2020
#

name: sram

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - sky130_sram_4kbyte_1rw1r_32x1024_8.sp
  - sky130_sram_4kbyte_1rw1r_32x1024_8.lvs.sp
  - sky130_sram_4kbyte_1rw1r_32x1024_8.v
  - sky130_sram_4kbyte_1rw1r_32x1024_8.lef
  - sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib
  - sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.db
  - sky130_sram_4kbyte_1rw1r_32x1024_8.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

# After copying the files over, we make one modification to the SRAM LEF file.
# Currently, the power pins on the SRAM macro have an attribute called SHAPE
# ABUTMENT, which prevents routing power and ground to its pins. We use sed to
# remove this line from the LEF file. For more information read the LEF
# documentation.

commands:
# The SRAM macros are cloned from https://github.com/efabless/sky130_sram_macros  
  - cp /tmp/praina/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.sp outputs/sky130_sram_4kbyte_1rw1r_32x1024_8.sp
  - cp /tmp/praina/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.lvs.sp outputs/sky130_sram_4kbyte_1rw1r_32x1024_8.lvs.sp
  - cp /tmp/praina/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.v outputs/sky130_sram_4kbyte_1rw1r_32x1024_8.v
  - cp /tmp/praina/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.lef outputs/sky130_sram_4kbyte_1rw1r_32x1024_8.lef
  - cp /tmp/praina/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib outputs/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib
  - cp /tmp/praina/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.gds outputs/sky130_sram_4kbyte_1rw1r_32x1024_8.gds
  - cp /tmp/praina/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.db outputs/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.db

  - sed -i '/SHAPE ABUTMENT/d' outputs/sky130_sram_4kbyte_1rw1r_32x1024_8.lef
