#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/mjpauly/repos/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name=user_proj_example

# Commands

cp inputs/design.pt.sdc inputs/design.pt.sdc-unmodified
rm inputs/design.pt.sdc
cp inputs/design.pt.sdc-unmodified inputs/design.pt.sdc
vim -T dumb --noplugin -n -S "fix_pt_appends.vim" "inputs/design.pt.sdc"
pt_shell -file pt.tcl
mkdir -p outputs && cd outputs
ln -sf ../design.sdf design.sdf

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

