# TODO: Set number of vectors parameter in python file and testbench from yml

name: testbench

inputs:
  - adk

outputs:
  - testbench.sv
  - test_vectors.txt
  - design.args
  - design.args.gls

commands:
  - cp GcdUnitTb.sv outputs/testbench.sv
  - python3 generate_test_vectors.py
  - cp test_vectors.txt outputs/test_vectors.txt
  - cp design.args outputs/design.args
  - cat design.args.gls inputs/adk/vcs_incdir.txt > outputs/design.args.gls
