name: testbench

outputs:
  - testbench.sv
  - testbench.v
  - layer_params.v
  - ifmap_data.txt
  - weight_data.txt
  - ofmap_data.txt
  - design.args

commands:
  #- python3.7 json_to_parameters.py -l layers/resnet_conv2_x_params_small.json
  #- python3.7 json_to_parameters.py -l layers/resnet_conv3_x_params_small.json
  - python3.7 json_to_parameters.py -l layers/resnet_conv4_x_params_small.json
  - mv layer_params.v outputs/
  - g++ -g -std=c++11 conv_tb.cpp -o conv_tb
  - ./conv_tb
  - mv ifmap_data.txt outputs/
  - mv weight_data.txt outputs/
  - mv ofmap_data.txt outputs/
  - cp conv_optimized_tb.v outputs/testbench.sv
  - cp conv_optimized_tb.v outputs/testbench.v
